In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a = np.array([[1,2,3],[3,4,5]])
print (a)

[[1 2 3]
 [3 4 5]]


In [8]:
list1 = [1, 24, 5, 7]
a = np.array(list1)
a

array([ 1, 24,  5,  7])

In [11]:
a=np.arange(10,100)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [13]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
a=np.linspace(0,20,5)
a

array([ 0.,  5., 10., 15., 20.])

In [16]:
#Restructure a Numpy array
a=np.zeros(8)
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a=a.reshape(2,2,2)
a

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
a.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
#Indexing and slicing
a=np.arange(2,20)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
a[6]

8

In [23]:
arr_slice=slice(1,10,2)
element=a[6]
element

8

In [24]:
print(a[arr_slice])

[ 3  5  7  9 11]


In [25]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
a[:5]

array([0, 1, 2, 3, 4])

In [28]:
#Index and slice multidimensional arrays
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [29]:
a.shape

(3, 3)

In [30]:
a[:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [31]:
a[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [32]:
#Attributes
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [33]:
a.shape

(3, 3)

In [34]:
a.ndim

2

In [35]:
a.itemsize

8

In [36]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [37]:
import tensorflow as tf

In [40]:
tf.__version__

'2.8.2'

In [42]:
a=tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [44]:
b=tf.constant(3)
c=tf.constant(5)

In [46]:
add=tf.add(a,b)
add

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [47]:
add.numpy()

5

In [49]:
sub=tf.subtract(a,b)
sub.numpy()

-1

In [50]:
mul=tf.multiply(c,a)
mul

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [51]:
mul.numpy()

10

In [52]:
tf.divide(a,c).numpy()

0.4

In [56]:
mean=tf.reduce_mean([a,b,c])
mean.numpy()

3

In [57]:
sum=tf.reduce_sum([a,b,c])
sum.numpy()

10

In [59]:
m1 = tf.constant([[1,2],[3,4]])
m2 = tf.constant([[1,2],[3,4]])

In [60]:
m1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [61]:
m2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [62]:
mat_mul=tf.matmul(m1,m2)